CONFIG_ZMK_USB_LOGGING=n
# Nazwa widoczna w menu Bluetooth
CONFIG_ZMK_KEYBOARD_NAME="Totem"

# Włączenie wsparcia dla Bluetooth
CONFIG_ZMK_BLE=y

# Zwiększenie mocy nadawania (kluczowe dla XIAO - domyślnie jest bardzo słaba)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Wymuszenie czyszczenia starych profilów przy starcie (opcjonalnie, jeśli nic nie pomaga)
# CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
